export const majorCareers: string[] = [
    "Software Developer",
    "Registered Nurse",
    "Accountant",
    "Marketing Manager",
    "Teacher",
    "Financial Advisor",
    "Engineer",
    "Graphic Designer",
    "Physical Therapist",
    "Sales Manager",
    "Human Resources Manager",
    "Civil Engineer",
    "Medical and Health Services Manager",
    "Operations Manager",
    "Social Worker",
    "Electrical Engineer",
    "Market Research Analyst",
    "Executive Assistant",
    "Pharmacist",
    "Dental Hygienist",
    "Web Developer",
    "Computer Systems Analyst",
    "Database Administrator",
    "Public Relations Specialist",
    "IT Manager",
    "Logistician",
    "Occupational Therapist",
    "Psychologist",
    "Physician Assistant",
    "Speech-Language Pathologist",
    "Construction Manager",
    "Software Quality Assurance Engineer",
    "Financial Analyst",
    "Business Analyst",
    "Data Scientist",
    "Environmental Engineer",
    "Nurse Practitioner",
    "Management Analyst",
    "Mechanical Engineering Technician",
    "Event Planner",
    "Medical Records Technician",
    "Market Research Analyst",
    "Substance Abuse Counselor",
    "Veterinary Technologist",
    "Cost Estimator",
    "Interpreter and Translator",
    "Fitness Trainer",
    "Social and Community Service Manager",
    "Marketing Manager"
];
